
services:
###> doctrine/doctrine-bundle ###
  database:
    image: mariadb:${MARIADB_VERSION:-10.4}
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE:-Momentum}
      MARIADB_ALLOW_EMPTY_ROOT_PASSWORD: "yes"
      TZ: Europe/Berlin
    command:
      - --default-time-zone=Europe/Berlin
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb-buffer-pool-size=536870912
      - --innodb-flush-log-at-trx-commit=2
      - --sql-mode=NO_ZERO_IN_DATE,NO_ZERO_DATE,NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/mysql:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/mysql:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
